--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/ChatThin
build-by-default: true
branches:
  - master
projects:
  ChatThin:
    projectId: 7492
    icon: "icon.png"
    lint:
      phpstan: true
...
